{"level":"error"}
{"level":"error"}
{"level":"error","message":"couldn't get info"}
{"level":"error","message":"couldn't get infocouldn't get info","stack":"Error: couldn't get info\n    at router.get (C:\\Users\\Angelo\\platform\\routes\\login.js:30:8)\n    at newFn (C:\\Users\\Angelo\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Angelo\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Angelo\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at adminAuth (C:\\Users\\Angelo\\platform\\middleware\\adminAuth.js:12:3)\n    at newFn (C:\\Users\\Angelo\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Angelo\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Angelo\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\Users\\Angelo\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\Users\\Angelo\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Angelo\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Angelo\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\Users\\Angelo\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\Users\\Angelo\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\Users\\Angelo\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\Users\\Angelo\\node_modules\\express\\lib\\router\\index.js:47:12)"}
{"level":"error","message":"couldn't get info.\ncouldn't get info.\n","stack":"Error: couldn't get info.\n\n    at router.get (C:\\Users\\Angelo\\platform\\routes\\login.js:30:8)\n    at newFn (C:\\Users\\Angelo\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Angelo\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Angelo\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at adminAuth (C:\\Users\\Angelo\\platform\\middleware\\adminAuth.js:12:3)\n    at newFn (C:\\Users\\Angelo\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Angelo\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Angelo\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\Users\\Angelo\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\Users\\Angelo\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Angelo\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Angelo\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\Users\\Angelo\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\Users\\Angelo\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\Users\\Angelo\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\Users\\Angelo\\node_modules\\express\\lib\\router\\index.js:47:12)"}
{"level":"error","message":"something failed during startup.something failed during startup.","stack":"Error: something failed during startup.\n    at Object.<anonymous> (C:\\Users\\Angelo\\platform\\index.js:27:7)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)"}
{"message":"Connected to MongoDB...","level":"info"}
{"message":"Connected to MongoDB...","level":"info"}
{"message":"Connected to MongoDB...","level":"info"}
{"message":"Connected to MongoDB...","level":"info"}
{"name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"error","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\Users\\Angelo\\node_modules\\mongodb-core\\lib\\topologies\\server.js:564:11)\n    at Pool.emit (events.js:189:13)\n    at Connection.<anonymous> (C:\\Users\\Angelo\\node_modules\\mongodb-core\\lib\\connection\\pool.js:317:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Socket.<anonymous> (C:\\Users\\Angelo\\node_modules\\mongodb-core\\lib\\connection\\connection.js:246:50)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
{"message":"Connected to MongoDB...","level":"info"}
{"message":"Connected to MongoDB...","level":"info"}
{"message":"Listening on port 3000...","level":"info"}
{"message":"Connected to MongoDB...","level":"info"}
{"message":"Listening on port 3000...","level":"info"}
{"message":"Connected to MongoDB...","level":"info"}
{"message":"Listening on port 3000...","level":"info"}
{"message":"Connected to MongoDB...","level":"info"}
{"message":"Listening on port 3000...","level":"info"}
{"message":"Connected to MongoDB...","level":"info"}
{"message":"Listening on port 3000...","level":"info"}
{"message":"Connected to MongoDB...","level":"info"}
{"message":"Listening on port 3000...","level":"info"}
{"message":"Connected to MongoDB...","level":"info"}
{"message":"Listening on port 3000...","level":"info"}
{"message":"Connected to MongoDB...","level":"info"}
{"message":"Listening on port 3000...","level":"info"}
{"message":"Connected to MongoDB...","level":"info"}
{"expose":true,"statusCode":400,"status":400,"body":"{\n\t\"school\": \"四川大学\",\n\t\"schoolId\": \"2015141443000\",\n\t\"phone\": \"18519810000\"\n\t\"password\": \"password123\"\n}","type":"entity.parse.failed","level":"error","message":"Unexpected string in JSON at position 76Unexpected string in JSON at position 76","stack":"SyntaxError: Unexpected string in JSON at position 76\n    at JSON.parse (<anonymous>)\n    at parse (C:\\Users\\Angelo\\platform\\node_modules\\body-parser\\lib\\types\\json.js:89:19)\n    at C:\\Users\\Angelo\\platform\\node_modules\\body-parser\\lib\\read.js:121:18\n    at invokeCallback (C:\\Users\\Angelo\\platform\\node_modules\\raw-body\\index.js:224:16)\n    at done (C:\\Users\\Angelo\\platform\\node_modules\\raw-body\\index.js:213:7)\n    at IncomingMessage.onEnd (C:\\Users\\Angelo\\platform\\node_modules\\raw-body\\index.js:273:7)\n    at IncomingMessage.emit (events.js:189:13)\n    at endReadableNT (_stream_readable.js:1103:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
{"ok":0,"errmsg":"cannot do raw queries on admin in atlas","code":8000,"codeName":"AtlasError","name":"MongoError","level":"error","message":"cannot do raw queries on admin in atlascannot do raw queries on admin in atlas","stack":"MongoError: cannot do raw queries on admin in atlas\n    at C:\\Users\\Angelo\\platform\\node_modules\\mongodb-core\\lib\\connection\\pool.js:581:63\n    at authenticateStragglers (C:\\Users\\Angelo\\platform\\node_modules\\mongodb-core\\lib\\connection\\pool.js:504:16)\n    at Connection.messageHandler (C:\\Users\\Angelo\\platform\\node_modules\\mongodb-core\\lib\\connection\\pool.js:540:5)\n    at emitMessageHandler (C:\\Users\\Angelo\\platform\\node_modules\\mongodb-core\\lib\\connection\\connection.js:310:10)\n    at TLSSocket.<anonymous> (C:\\Users\\Angelo\\platform\\node_modules\\mongodb-core\\lib\\connection\\connection.js:453:17)\n    at TLSSocket.emit (events.js:189:13)\n    at addChunk (_stream_readable.js:284:12)\n    at readableAddChunk (_stream_readable.js:265:11)\n    at TLSSocket.Readable.push (_stream_readable.js:220:10)\n    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)"}
{"ok":0,"errmsg":"cannot do raw queries on admin in atlas","code":8000,"codeName":"AtlasError","name":"MongoError","level":"error","message":"cannot do raw queries on admin in atlascannot do raw queries on admin in atlas","stack":"MongoError: cannot do raw queries on admin in atlas\n    at C:\\Users\\Angelo\\platform\\node_modules\\mongodb-core\\lib\\connection\\pool.js:581:63\n    at authenticateStragglers (C:\\Users\\Angelo\\platform\\node_modules\\mongodb-core\\lib\\connection\\pool.js:504:16)\n    at Connection.messageHandler (C:\\Users\\Angelo\\platform\\node_modules\\mongodb-core\\lib\\connection\\pool.js:540:5)\n    at emitMessageHandler (C:\\Users\\Angelo\\platform\\node_modules\\mongodb-core\\lib\\connection\\connection.js:310:10)\n    at TLSSocket.<anonymous> (C:\\Users\\Angelo\\platform\\node_modules\\mongodb-core\\lib\\connection\\connection.js:453:17)\n    at TLSSocket.emit (events.js:189:13)\n    at addChunk (_stream_readable.js:284:12)\n    at readableAddChunk (_stream_readable.js:265:11)\n    at TLSSocket.Readable.push (_stream_readable.js:220:10)\n    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)"}
{"level":"error","message":"bcrypt.gpasswordenSalt is not a functionbcrypt.gpasswordenSalt is not a function","stack":"TypeError: bcrypt.gpasswordenSalt is not a function\n    at router.put (C:\\Users\\Angelo\\platform\\routes\\login.js:57:28)\n    at newFn (C:\\Users\\Angelo\\platform\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at auth (C:\\Users\\Angelo\\platform\\middleware\\auth.js:11:3)\n    at newFn (C:\\Users\\Angelo\\platform\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\Users\\Angelo\\platform\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\index.js:281:22\n    at param (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\index.js:354:14)\n    at param (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\index.js:365:14)\n    at Function.process_params (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\index.js:410:3)\n    at next (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\index.js:275:10)"}
{"level":"error","message":"user is not defineduser is not defined","stack":"ReferenceError: user is not defined\n    at validate (C:\\Users\\Angelo\\platform\\models\\course.js:69:23)\n    at router.post (C:\\Users\\Angelo\\platform\\routes\\course.js:70:20)\n    at newFn (C:\\Users\\Angelo\\platform\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at auth (C:\\Users\\Angelo\\platform\\middleware\\auth.js:11:3)\n    at newFn (C:\\Users\\Angelo\\platform\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\Users\\Angelo\\platform\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\index.js:174:3)"}
{"level":"error","message":"user is not defineduser is not defined","stack":"ReferenceError: user is not defined\n    at validate (C:\\Users\\Angelo\\platform\\models\\course.js:69:23)\n    at router.post (C:\\Users\\Angelo\\platform\\routes\\course.js:70:20)\n    at newFn (C:\\Users\\Angelo\\platform\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at auth (C:\\Users\\Angelo\\platform\\middleware\\auth.js:11:3)\n    at newFn (C:\\Users\\Angelo\\platform\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\Users\\Angelo\\platform\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\Users\\Angelo\\platform\\node_modules\\express\\lib\\router\\index.js:174:3)"}
{"message":"Cast to ObjectId failed for value \"me\" at path \"_id\" for model \"User\"Cast to ObjectId failed for value \"me\" at path \"_id\" for model \"User\"","name":"CastError","stringValue":"\"me\"","kind":"ObjectId","value":"me","path":"_id","level":"error","stack":"CastError: Cast to ObjectId failed for value \"me\" at path \"_id\" for model \"User\"\n    at new CastError (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\error\\cast.js:29:11)\n    at ObjectId.cast (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schema\\objectid.js:242:11)\n    at ObjectId.SchemaType.applySetters (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schematype.js:849:12)\n    at ObjectId.SchemaType._castForQuery (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schematype.js:1252:15)\n    at ObjectId.SchemaType.castForQuery (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schematype.js:1242:15)\n    at ObjectId.SchemaType.castForQueryWrapper (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schematype.js:1221:15)\n    at cast (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\cast.js:307:32)\n    at model.Query.Query.cast (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\query.js:4340:12)\n    at model.Query.Query._castConditions (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\query.js:1723:10)\n    at model.Query.<anonymous> (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\query.js:1976:8)\n    at model.Query._wrappedThunk [as _findOne] (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\helpers\\query\\wrapThunk.js:16:8)\n    at process.nextTick (C:\\Users\\Angelo\\platform\\node_modules\\kareem\\index.js:369:33)\n    at process._tickCallback (internal/process/next_tick.js:61:11)"}
{"message":"Cast to ObjectId failed for value \"me\" at path \"_id\" for model \"User\"Cast to ObjectId failed for value \"me\" at path \"_id\" for model \"User\"","name":"CastError","stringValue":"\"me\"","kind":"ObjectId","value":"me","path":"_id","level":"error","stack":"CastError: Cast to ObjectId failed for value \"me\" at path \"_id\" for model \"User\"\n    at new CastError (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\error\\cast.js:29:11)\n    at ObjectId.cast (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schema\\objectid.js:242:11)\n    at ObjectId.SchemaType.applySetters (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schematype.js:849:12)\n    at ObjectId.SchemaType._castForQuery (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schematype.js:1252:15)\n    at ObjectId.SchemaType.castForQuery (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schematype.js:1242:15)\n    at ObjectId.SchemaType.castForQueryWrapper (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schematype.js:1221:15)\n    at cast (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\cast.js:307:32)\n    at model.Query.Query.cast (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\query.js:4340:12)\n    at model.Query.Query._castConditions (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\query.js:1723:10)\n    at model.Query.<anonymous> (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\query.js:1976:8)\n    at model.Query._wrappedThunk [as _findOne] (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\helpers\\query\\wrapThunk.js:16:8)\n    at process.nextTick (C:\\Users\\Angelo\\platform\\node_modules\\kareem\\index.js:369:33)\n    at process._tickCallback (internal/process/next_tick.js:61:11)"}
{"message":"Cast to ObjectId failed for value \"me\" at path \"_id\" for model \"User\"Cast to ObjectId failed for value \"me\" at path \"_id\" for model \"User\"","name":"CastError","stringValue":"\"me\"","kind":"ObjectId","value":"me","path":"_id","level":"error","stack":"CastError: Cast to ObjectId failed for value \"me\" at path \"_id\" for model \"User\"\n    at new CastError (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\error\\cast.js:29:11)\n    at ObjectId.cast (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schema\\objectid.js:242:11)\n    at ObjectId.SchemaType.applySetters (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schematype.js:849:12)\n    at ObjectId.SchemaType._castForQuery (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schematype.js:1252:15)\n    at ObjectId.SchemaType.castForQuery (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schematype.js:1242:15)\n    at ObjectId.SchemaType.castForQueryWrapper (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schematype.js:1221:15)\n    at cast (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\cast.js:307:32)\n    at model.Query.Query.cast (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\query.js:4340:12)\n    at model.Query.Query._castConditions (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\query.js:1723:10)\n    at model.Query.<anonymous> (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\query.js:1976:8)\n    at model.Query._wrappedThunk [as _findOne] (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\helpers\\query\\wrapThunk.js:16:8)\n    at process.nextTick (C:\\Users\\Angelo\\platform\\node_modules\\kareem\\index.js:369:33)\n    at process._tickCallback (internal/process/next_tick.js:61:11)"}
{"message":"Cast to ObjectId failed for value \"me\" at path \"_id\" for model \"User\"Cast to ObjectId failed for value \"me\" at path \"_id\" for model \"User\"","name":"CastError","stringValue":"\"me\"","kind":"ObjectId","value":"me","path":"_id","level":"error","stack":"CastError: Cast to ObjectId failed for value \"me\" at path \"_id\" for model \"User\"\n    at new CastError (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\error\\cast.js:29:11)\n    at ObjectId.cast (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schema\\objectid.js:242:11)\n    at ObjectId.SchemaType.applySetters (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schematype.js:849:12)\n    at ObjectId.SchemaType._castForQuery (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schematype.js:1252:15)\n    at ObjectId.SchemaType.castForQuery (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schematype.js:1242:15)\n    at ObjectId.SchemaType.castForQueryWrapper (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schematype.js:1221:15)\n    at cast (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\cast.js:307:32)\n    at model.Query.Query.cast (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\query.js:4340:12)\n    at model.Query.Query._castConditions (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\query.js:1723:10)\n    at model.Query.<anonymous> (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\query.js:1976:8)\n    at model.Query._wrappedThunk [as _findOne] (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\helpers\\query\\wrapThunk.js:16:8)\n    at process.nextTick (C:\\Users\\Angelo\\platform\\node_modules\\kareem\\index.js:369:33)\n    at process._tickCallback (internal/process/next_tick.js:61:11)"}
{"expose":true,"statusCode":400,"status":400,"body":"{\n\t\"name\": \"naq\".\n\t\"year\": 2015,\n\t\"department\": \"EE\",\n\t\"major\": \"telecom\"\n}","type":"entity.parse.failed","level":"error","message":"Unexpected token . in JSON at position 16Unexpected token . in JSON at position 16","stack":"SyntaxError: Unexpected token . in JSON at position 16\n    at JSON.parse (<anonymous>)\n    at parse (C:\\Users\\Angelo\\platform\\node_modules\\body-parser\\lib\\types\\json.js:89:19)\n    at C:\\Users\\Angelo\\platform\\node_modules\\body-parser\\lib\\read.js:121:18\n    at invokeCallback (C:\\Users\\Angelo\\platform\\node_modules\\raw-body\\index.js:224:16)\n    at done (C:\\Users\\Angelo\\platform\\node_modules\\raw-body\\index.js:213:7)\n    at IncomingMessage.onEnd (C:\\Users\\Angelo\\platform\\node_modules\\raw-body\\index.js:273:7)\n    at IncomingMessage.emit (events.js:189:13)\n    at endReadableNT (_stream_readable.js:1103:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
{"message":"Cast to ObjectId failed for value \"me\" at path \"_id\" for model \"User\"Cast to ObjectId failed for value \"me\" at path \"_id\" for model \"User\"","name":"CastError","stringValue":"\"me\"","kind":"ObjectId","value":"me","path":"_id","level":"error","stack":"CastError: Cast to ObjectId failed for value \"me\" at path \"_id\" for model \"User\"\n    at new CastError (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\error\\cast.js:29:11)\n    at ObjectId.cast (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schema\\objectid.js:242:11)\n    at ObjectId.SchemaType.applySetters (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schematype.js:849:12)\n    at ObjectId.SchemaType._castForQuery (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schematype.js:1252:15)\n    at ObjectId.SchemaType.castForQuery (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schematype.js:1242:15)\n    at ObjectId.SchemaType.castForQueryWrapper (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\schematype.js:1221:15)\n    at cast (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\cast.js:307:32)\n    at model.Query.Query.cast (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\query.js:4340:12)\n    at castQuery (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\query.js:4192:18)\n    at model.Query.Query._findAndModify (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\query.js:3204:23)\n    at model.Query.<anonymous> (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\query.js:2831:8)\n    at model.Query._wrappedThunk [as _findOneAndUpdate] (C:\\Users\\Angelo\\platform\\node_modules\\mongoose\\lib\\helpers\\query\\wrapThunk.js:16:8)\n    at process.nextTick (C:\\Users\\Angelo\\platform\\node_modules\\kareem\\index.js:369:33)\n    at process._tickCallback (internal/process/next_tick.js:61:11)"}
{"level":"error","message":"User.findById is not a functionUser.findById is not a function","stack":"TypeError: User.findById is not a function\n    at router.post (C:\\Users\\Angelo\\platform\\routes\\course.js:81:26)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
{"driver":true,"name":"MongoError","index":0,"code":11000,"errmsg":"E11000 duplicate key error collection: platform.courses index: instructor_1 dup key: { : ObjectId('5c7facd314208137941e34b3') }","level":"error","message":"E11000 duplicate key error collection: platform.courses index: instructor_1 dup key: { : ObjectId('5c7facd314208137941e34b3') }E11000 duplicate key error collection: platform.courses index: instructor_1 dup key: { : ObjectId('5c7facd314208137941e34b3') }","stack":"MongoError: E11000 duplicate key error collection: platform.courses index: instructor_1 dup key: { : ObjectId('5c7facd314208137941e34b3') }\n    at Function.create (C:\\Users\\Angelo\\platform\\node_modules\\mongodb-core\\lib\\error.js:43:12)\n    at toError (C:\\Users\\Angelo\\platform\\node_modules\\mongodb\\lib\\utils.js:149:22)\n    at coll.s.topology.insert (C:\\Users\\Angelo\\platform\\node_modules\\mongodb\\lib\\operations\\collection_ops.js:859:39)\n    at C:\\Users\\Angelo\\platform\\node_modules\\mongodb-core\\lib\\connection\\pool.js:532:18\n    at process._tickCallback (internal/process/next_tick.js:61:11)"}
{"level":"error","message":"User.findOne is not a functionUser.findOne is not a function","stack":"TypeError: User.findOne is not a function\n    at router.post (C:\\Users\\Angelo\\platform\\routes\\course.js:81:26)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
